@host = http://localhost:5113

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZmM0ZjgxNC1lNGFmLTRjMjYtYjQ2Yi04YWVmNjBlZDNjNWMiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaWkiLCJmYW1pbHlfbmFtZSI6Ik1hbnRpbmFiYW5kIiwianRpIjoiYmVjMWM4MzAtYWM5Mi00N2JiLTkwNzctNWQ4MTRmOTMwNmExIiwiZXhwIjoxNzA4NjU3NDk5LCJpc3MiOiJCdWJlckRpbm5lcnMiLCJhdWQiOiJCdWJlckRpbm5lciJ9.xwwxdzHPGGoa70hkW0hq5UG1uhhz38oFvtX3-MJb68Q


###