@host = http://localhost:5113

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Amichaii",
    "lastName": "Mantinaband",
    "email": "amichai@mantiband.com",
    "password": "Amiko1232!"
}

###
